---
version: '3'
networks:
  bridge-optima:
    driver: bridge
  bridge-irydium:
    driver: bridge
services:
  web-optima:
    image: "xwiki:10.9-mysql-tomcat"
    container_name: xwiki-web-optima
    depends_on:
      - db-optima
    ports:
      - "8000:8080"
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_HOST=xwiki-db-optima
    volumes:
      - xwiki-optima-data:/usr/local/xwiki
    networks:
      - bridge-optima
  db-optima:
    image: "mysql:5.7"
    container_name: xwiki-db-optima
    volumes:
      - ./xwiki.cnf:/etc/mysql/conf.d/xwiki.cnf
      - mysql-optima-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xwiki
      - MYSQL_USER=xwiki
      - MYSQL_PASSWORD=xwiki
      - MYSQL_DATABASE=xwiki
    networks:
      - bridge-optima
  web-irudium:
    image: "xwiki:10.9-mysql-tomcat"
    container_name: xwiki-web-irydium
    depends_on:
      - db-irydium
    ports:
      - "8080:8080"
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_HOST=xwiki-db-irydium
    volumes:
      - xwiki-irydium-data:/usr/local/xwiki
    networks:
      - bridge-irydium
  db-irydium:
    image: "mysql:5.7"
    container_name: xwiki-db-irydium
    volumes:
      - ./xwiki.cnf:/etc/mysql/conf.d/xwiki.cnf
      - mysql-irydium-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xwiki
      - MYSQL_USER=xwiki
      - MYSQL_PASSWORD=xwiki
      - MYSQL_DATABASE=xwiki
    networks:
      - bridge-irydium
volumes:
  mysql-optima-data: {}
  xwiki-optima-data: {}
  mysql-irydium-data: {}
  xwiki-irydium-data: {}
