---
version: '3'
networks:
  bridge-optima:
    driver: bridge
  bridge-irydium:
    driver: bridge
services:
  web-optima:
    image: "xwiki:10.9-postgres-tomcat"
    container_name: xwiki-web-optima
    depends_on:
      - db-optima
    ports:
      - "8000:8080"
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_HOST=xwiki-db-optima
    volumes:
      - xwiki-optima-data:/usr/local/xwiki
    networks:
      - bridge-optima
  db-optima:
    image: "postgres:9.5"
    container_name: xwiki-db-optima
    volumes:
      - postgres-optima-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_ROOT_PASSWORD=xwiki
      - POSTGRES_PASSWORD=xwiki
      - POSTGRES_USER=xwiki
      - POSTGRES_DB=xwiki
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    networks:
      - bridge-optima
  web-irudium:
    image: "xwiki:10.9-postgres-tomcat"
    container_name: xwiki-web-irydium
    depends_on:
      - db-irydium
    ports:
      - "8080:8080"
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_HOST=xwiki-db-irydium
    volumes:
      - xwiki-irydium-data:/usr/local/xwiki
    networks:
      - bridge-irydium
  db-irydium:
    image: "postgres:9.5"
    container_name: xwiki-db-irydium
    volumes:
      - postgres-irydium-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_ROOT_PASSWORD=xwiki
      - POSTGRES_PASSWORD=xwiki
      - POSTGRES_USER=xwiki
      - POSTGRES_DB=xwiki
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    networks:
      - bridge-irydium
volumes:
  postgres-optima-data: {}
  xwiki-optima-data: {}
  postgres-irydium-data: {}
  xwiki-irydium-data: {}
