---
- name: Set up git configuration
  apt: name=git state=latest
  become: yes

- name: Create proj directory
  file: path={{ app_dir }} state=directory owner=root group=root mode=0775
  become: yes

- name: Clone or pull the latest code
  git: repo={{ git_repo }}
        dest={{ app_dir }}
        recursive=yes
        accept_hostkey=yes
        version={{ git_branch }}
