---
- name: Ensure .ssh directory exists
  file: 
    dest: /root/.ssh
    mode: 0700
    owner: root
    state: directory

- name: Install ssh key
  copy:
    src: /home/{{ operator_name }}/.ssh/id_rsa
    dest: /root/.ssh/id_rsa
    mode: 0600
    owner: root
